# Generated by Django 5.2 on 2025-05-02 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=20, unique=True)),
                ('ga', models.IntegerField()),
                ('weight', models.FloatField()),
                ('aga_sga_lga', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('tob', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('feeds', models.CharField(blank=True, max_length=100, null=True)),
                ('cal', models.FloatField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, null=True)),
                ('kmc', models.FloatField(blank=True, null=True)),
                ('gain_loss', models.CharField(blank=True, max_length=50, null=True)),
                ('acute_events', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.patient')),
            ],
        ),
    ]
