# Generated by Django 5.2 on 2025-05-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_entry_caffeine_entry_calcium_entry_desaturations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='piomi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
