# Generated by Django 5.2 on 2025-05-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_entry_piomi'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='mode_of_feeding',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
