from django.db import models

class Patient(models.Model):
    patient_id = models.CharField(max_length=20, unique=True)
    ga = models.IntegerField()
    weight = models.FloatField()
    aga_sga_lga = models.CharField(max_length=10)
    sex = models.CharField(max_length=10)
    dob = models.DateField()
    tob = models.TimeField(null=True, blank=True)
    name = models.CharField(max_length=100, null=True, blank=True)

class Entry(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='entries')
    date = models.DateField()
    kmc = models.FloatField(null=True, blank=True)
    cal = models.FloatField(null=True, blank=True)
    protein = models.FloatField(null=True, blank=True)
    weight = models.FloatField(null=True, blank=True)
    tfr = models.CharField(max_length=100, null=True, blank=True)
    feeds = models.CharField(max_length=100, null=True, blank=True)
    dol = models.IntegerField(null=True, blank=True)
    pma = models.CharField(max_length=100, null=True, blank=True)
    nns = models.CharField(max_length=100, null=True, blank=True)
    gain_loss = models.CharField(max_length=100, null=True, blank=True)
    hmf = models.CharField(max_length=100, null=True, blank=True)
    type_of_milk = models.CharField(max_length=100, null=True, blank=True)
    early_intervention = models.CharField(max_length=1, null=True, blank=True)
    calcium = models.CharField(max_length=100, null=True, blank=True)
    phosphorus = models.CharField(max_length=100, null=True, blank=True)
    vit_d = models.CharField(max_length=100, null=True, blank=True)
    iron = models.CharField(max_length=100, null=True, blank=True)
    zinc = models.CharField(max_length=100, null=True, blank=True)
    caffeine = models.CharField(max_length=100, null=True, blank=True)
    resp_support = models.CharField(max_length=100, null=True, blank=True)
    desaturations = models.CharField(max_length=100, null=True, blank=True)
    acute_events = models.TextField(null=True, blank=True)
    piomi = models.CharField(max_length=100, null=True, blank=True)
    mode_of_feeding = models.CharField(max_length=100, null=True, blank=True)

